[package]
name = "kwikpaste-ext-ocr"
version = "1.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
kwikpaste-ext-protocol = { path = "../kwikpaste-ext-protocol" }

[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = ["Media_Ocr", "Graphics_Imaging", "Storage", "Storage_Streams", "Globalization", "Foundation", "Foundation_Collections", "Win32_System_WinRT", "Win32_System_Threading"]

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true
objc2.workspace = true
objc2-vision = { version = "0.3", default-features = false, features = ["std", "VNRecognizeTextRequest", "VNRequest", "VNRequestHandler", "VNObservation", "VNTypes", "objc2-core-graphics", "objc2-image-io"] }
objc2-image-io = { version = "0.3", default-features = false, features = ["std", "CGImageSource", "objc2-core-graphics"] }
objc2-core-foundation = { version = "0.3", default-features = false, features = ["std", "CFURL", "CFString", "CFDictionary", "CFNumber"] }
objc2-core-graphics = { workspace = true, features = ["std", "CGImage"] }
objc2-foundation = { workspace = true, features = ["std", "NSArray", "NSEnumerator", "NSDictionary", "NSString", "NSError"] }

[dev-dependencies]
image.workspace = true
tempfile.workspace = true

[lints]
workspace = true
